# write mock - push - ignore
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
DASH_CACHE_DIR = DATA_DIR

RAW_DATA_DIR = DATA_DIR
PROCESSED_DATA_DIR = DATA_DIR
NEW_PROCESSED_DATA_DIR = DATA_DIR

RAW_FORMS_DIR = DATA_DIR
PROCESSED_FORMS_DIR = DATA_DIR
UNIFIED_FORMS_FILE = os.path.join(PROCESSED_FORMS_DIR, 'Weizmann_COVID19_Survey_data.csv')

GOOGLE_FORM_RAW_DIR = DATA_DIR
GOOGLE_FORM_PROCESSED_DIR = DATA_DIR

BOT_RAW_DIR = DATA_DIR
BOT_PROCESSED_DIR = DATA_DIR

PATIENTS_RAW_DIR = DATA_DIR
PATIENTS_PROCESSED_DIR = DATA_DIR

UTILITY_DATA = DATA_DIR
LAMAS_DATA = DATA_DIR

LAMAS_NEIGHBERHOOD_DATA = DATA_DIR
# LAMAS_CITIES_DATA = os.path.join(LAMAS_DATA, 'cities_lms_features.csv')


OUT_DIR = os.path.join(os.path.dirname(__file__), 'out')
